$(document).ready(function() {
  var articles = $("#articles");
  var searchUrl = "https://en.wikipedia.org/w/api.php";
  var toSearch = "";

  var ajaxArticleData = function() {
    $.ajax({
      url: searchUrl,
      dataType: "jsonp",
      data: {
        //main parameters
        action: "query",
        format: "json",

        generator: "search",
        //parameters for generator
        gsrsearch: toSearch,
        gsrnamespace: 0,
        gsrlimit: 1,

        prop: "extracts|pageimages",
        //parameters for extracts
        explaintext: true,
        exintro: true,

        //parameters for pageimages
        piprop: "thumbnail",
        pilimit: "max",
        pithumbsize: 200
      },
      success: function(json) {
        var pages = json.query.pages;
        $.map(pages, function(page) {
          var pageElement = $("#articles");

          //get the article image (if exists)
          if (page.thumbnail)
            $("#plantimage").attr("src", page.thumbnail.source);

          //get the article text
          pageElement.append($("<p>").text(page.extract));

          // pageElement.append($('<hr>'));

          articles.append(pageElement);
        });
      }
    });
  };

  const plantSciDict = {
    "African Cabbage": "Cleome_gynandra",
    "Asam Gelugur": "Garnicia_atroviridis",
    "Ambarella": "",
    "Green Amaranth": "",
    "Belimbing Buluh": "",
    "Brazil Nut": "",
    "Beluntas": "",
    "Bambara Groundnut DipC": "",
    "Green Cabbage": "",
    "Cucumber Tree": "",
    "Chinese Cabbage": "",
    "Carob": "",
    "Chiku": "",
    "French Bean": "",
    "Cowpea": "",
    "Chickpea": "",
    "Cat's Whiskers": "",
    "Dabai": "",
    "Engkabang Jantong": "",
    "Fonio": "",
    "Finger Millet": "",
    "Foxtail Millet": "",
    "Groundnut": "",
    "Gandarusa": "",
    "Hyacinth Bean": "",
    "Jute": "",
    "Kundang": "",
    "Keladi Kemoyang": "",
    "Leucaena":" ",
    "Moringa": "",
    "Mashua": "",
    "Nipa": "",
    "Napier Grass": "",
    "Okra": "",
    "Pigeonpea": "",
    "Peria Pantai": "",
    "Pulasan": "",
    "Proso Millet": "",
    "Pearl Millet": "",
    "Quinoa": "",
    "Soursop": "",
    "Salam": "",
    "Sambung nyawa": "",
    "Soybean": "",
    "Sago": "",
    "Sorghum": "",
    "Swamp Cabbage": "",
    "Taro (Cocoyam)": "",
    "Teff": "",
    "Winged Bean": "",
    "White Yamv": "",
    "Yautia": "",
    "Banana": "",
    "Betel Leaves": "",
    "Bird's Eye Chilli": "",
    "Bitter Bean": "",
    "Bitter Gourd": "",
    "Kai Choy/Bitter Mustard Greens": "",
    "Breadfruit": "",
    "Calabash": "",
    "Cassava": "",
    "Cat's Eye Fruitv": "",
    "Cempedak": "",
    "Capsicum": "",
    "Chinese Chives": "",
    "Red Chilli": "",
    "Cocoa": "",
    "Coconut": "",
    "Maize": "",
    "Cucumberv": "",
    "Curry Leaf": "",
    "Jering": "",
    "Dokong": "",
    "Red Dragon Fruit": "",
    "Duku": "",
    "Durian": "",
    "Long Purple Eggplant": "",
    "Fig Plant": "",
    "Finger Root": "",
    "Pandan Wangi": "",
    "Galangal": "",
    "Green Spinach": "",
    "Guava": "",
    "Rambai": "",
    "Jackfruit Tekam Yellow (J33)": "",
    "Horse Mango": "",
    "Indian Pennywort": "",
    "Jackfruit": "",
    "Kaffir Lime": "",
    "Kelulut Honey Bee": "",
    "Key Lime": "",
    "Kuini": "",
    "Lansons": "",
    "Lemongrass": "",
    "Limau Madu": "",
    "Calamondin": "",
    "Long Beans": "",
    "Indian Mulberry": "",
    "Mango": "",
    "Mangosteen": "",
    "Oil Palm": "",
    "Oyster Mushroom": "",
    "Paddy": "",
    "Papaya": "",
    "Signal Grass": "",
    "Petola Segi": "",
    "Pineapple": "",
    "Pomelo": "",
    "Rambutan": "",
    "Bayam Merah": "",
    "Roselle": "",
    "Round Eggplant": "",
    "Rubber": "",
    "Scallion": "",
    "Snake Fruit": "",
    "Spider Flower": "",
    "Star Goosebery": "",
    "Stevia": "",
    "Sugarcane": "",
    "Sweet Pumpkin": "",
    "Sweet Potato": "",
    "Tamarind": "",
    "Sweet Basil": "",
    "Torch Ginger": "",
    "Turmeric": "",
    "Vietnamese Coriander": "",
    "Water Apple": "",
    "Watermelon": "",
    "Winter Melon": "",
    "Yellow Sugarcane": "",
    "Choy Sum/Chinese flowering cabbage": "",
    "Bambara Groundnut S19": "",
    "Josephine Pineapple": "",
    "Sarawak Pineapple": "",
    "Black Gram": "",
    "Morris Pineapple": "",
    "Sesbania": "",
    "Egyptian sesban": "",
    "Chinese Jujube": "",
    "Indian Jujube": "",
    "Bud Flower Mucuna": "",
    "Velvet Bean": "",
    "Bamboo Shoot": "",
    "Safou": "",
    "Monkey Orange": "",
    "Cardamom": "",
    "Bambara Groundnut": "",
    "Avocado": "",
    "Custard Apple": "",
    "Indian-gooseberry": "",
    "Malay-apple": "",
    "Rose-apple": "",
    "Sugar-apple": "",
    "Pili Nut": "",
    "Areca Palm": "",
    "Java-plum": "",
    "Powder-puff Tree": "",
    "Pitanga": "",
    "Pomegranate": "",
    "Cashew": "",
    "Common Wheat": "",
    "Arabica Coffee": "",
    "Mandarin Orange": "",
    "Navel Orange": "",
    "Apple": "",
    "Broccoli": "",
    "Cauliflower": "",
    "Grape": "",
    "Carrot": "",
    "Potato": "",
    "N/A (Not Applicable)": "",
    "White Pea": "",
    "Apricot": "",
    "Sesame": "",
    "Wild Almond": "",
    "Lentil": "",
    "Moth-bean": "",
    "Tepary bean": "",
    "Cotton": "",
    "Sugar Beet": "",
    "Common Sunflower": "",
    "Tomato": "",
    "Barley": "",
    "Rice Bean": "",
    "Lima Bean": "",
    "Mung Bean": "",
    "Garden Pea": "",
    "Fava Bean": "",
    "Hungarian Vetch": "",
    "Common Vetch": "",
    "Bambara Groundnut ExSokoto": ""
  };

  $("#search_btn").click(function() {
    var value = $("#crop").val();
    toSearch = plantSciDict[value];
    articles.empty();
    ajaxArticleData();
  });
});
